var translates = {
   'restaurant' : 'Reštaurácia',
   'fire_station' : 'Požiarná zbrojnica',
   'post_office' : 'Pošta',
   'bank' : 'Banka',
   'place_of_worship' : 'Kostol',
   'post_box' : 'Poštová schránka',
   'ice_cream' : 'Zmrzlináreň',
   'nursery_school' : 'Škôlka',
   'cafe' : 'Kaviareň',
   'prison' : 'Väzenie',
   'theatre' : 'Divadlo',
   'university' : 'Univerzita',
   'nightclub' : 'Nočný klub',
   'cinema' : 'Kino',
   'dentist' : 'Zubná ambulancia',
   'bus_station' : 'Autobusová zástavka',
   'gym' : 'Telocvičňa',
   'marketplace' : 'Trhovisko',
   'sauna' : 'Sauna',
   'college' : 'Vysoká škola',
   'fuel' : 'Benzinka',
   'hospital' : 'Nemocnica',
   'pub' : 'Hostinec',
   'funeral_home' : 'Dom smútku',
   'driving_school' : 'Autoškola',
   'car_rental' : 'Požičovňa aut',
   'police' : 'Policajná stanica',
   'library' : 'Knižnica',
   'school' : 'Požičovňa aut',
   'fast_food' : 'Fast food',
   'parking' : 'Parkovisko',
}